Portfolio part 2
M1rn4/Set-up-adn-mobile-first pull request #3
Opened 2022-09-25 02:13 UTC by M1rn4

# In this project I worked on the following activities: 
- I add more information on the HTML and CSS files 
- I used images, grid, and flexbox
- I used the linters

2022-09-25 03:10 UTC, roshan-bajgain requested changes
Hi @M1rn4, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-25 03:10 UTC, roshan-bajgain commented on index.html
> +            </ul>
- [ ] I would suggest you please stick as much as possible to the Figma design. You missed `counter` a small `.` please implement it. See the image below for reference
### Figma design
 
![figma](https://user-images.githubusercontent.com/81727988/192126288-d3258cd0-3504-4015-8ad2-a3d54127722f.png)
### You design
![your](https://user-images.githubusercontent.com/81727988/192126293-bcb5670e-553c-4448-ab35-a6d75e8d79f3.png)

2022-09-25 03:10 UTC, roshan-bajgain commented on index.html
> +                <li><a href="#" class="works_list">2015</a></li>
- [ ] I would suggest you please stick as much as possible to the Figma design. You missed `counter` a small `.` please implement it. See the image below for reference
### Figma design
 
![figma](https://user-images.githubusercontent.com/81727988/192126288-d3258cd0-3504-4015-8ad2-a3d54127722f.png)
### You design
![your](https://user-images.githubusercontent.com/81727988/192126293-bcb5670e-553c-4448-ab35-a6d75e8d79f3.png)

2022-09-25 03:10 UTC, roshan-bajgain commented on index.html
> +            </ul>
- [ ] I would suggest you please stick as much as possible to the Figma design. You missed `counter` a small `.` please implement it. See the image below for reference
### Figma design
 
![figma](https://user-images.githubusercontent.com/81727988/192126288-d3258cd0-3504-4015-8ad2-a3d54127722f.png)
### You design
![your](https://user-images.githubusercontent.com/81727988/192126293-bcb5670e-553c-4448-ab35-a6d75e8d79f3.png)

2022-09-25 03:10 UTC, roshan-bajgain commented on index.html
> +            </ul>
- [ ] I would suggest you please stick as much as possible to the Figma design. You missed `counter` a small `.` please implement it. See the image below for reference
### Figma design
 
![figma](https://user-images.githubusercontent.com/81727988/192126288-d3258cd0-3504-4015-8ad2-a3d54127722f.png)
### You design
![your](https://user-images.githubusercontent.com/81727988/192126293-bcb5670e-553c-4448-ab35-a6d75e8d79f3.png)

2022-09-25 03:10 UTC, roshan-bajgain commented on index.html
> +                <p class="lang_skill">javaScript</p>
- [ ] I would suggest you please use the same background provided by microverse. See the image below for reference
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/192126381-c1ca8ae2-329e-4ea7-b9d9-43e007223e73.png)
### You design
![yourrrrrrrr](https://user-images.githubusercontent.com/81727988/192126388-cfcdecca-3280-4a00-afd5-e0ab7cdb1f3e.png)

2022-09-25 03:10 UTC, roshan-bajgain commented on index.html
> +                <p class="lang_skill">javaScript</p>
- [ ] I would suggest you please use the same background provided by microverse. See the image below for reference
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/192126381-c1ca8ae2-329e-4ea7-b9d9-43e007223e73.png)
### You design
![yourrrrrrrr](https://user-images.githubusercontent.com/81727988/192126388-cfcdecca-3280-4a00-afd5-e0ab7cdb1f3e.png)

2022-09-25 03:10 UTC, roshan-bajgain commented on index.html
> +            </div>
- [ ] I would suggest you please use the same background provided by microverse. See the image below for reference
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/192126381-c1ca8ae2-329e-4ea7-b9d9-43e007223e73.png)
### You design
![yourrrrrrrr](https://user-images.githubusercontent.com/81727988/192126388-cfcdecca-3280-4a00-afd5-e0ab7cdb1f3e.png)

2022-09-25 03:10 UTC, roshan-bajgain commented on index.html
> +            </div>
- [ ] I would suggest you please use the same background provided by microverse. See the image below for reference
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/192126381-c1ca8ae2-329e-4ea7-b9d9-43e007223e73.png)
### You design
![yourrrrrrrr](https://user-images.githubusercontent.com/81727988/192126388-cfcdecca-3280-4a00-afd5-e0ab7cdb1f3e.png)

2022-09-25 03:10 UTC, roshan-bajgain commented on index.html
> +                <p class="lang_skill">javaScript</p>
- [ ] The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list ul and each of them a li. please implement it

2022-09-25 03:10 UTC, roshan-bajgain commented on index.html
> +                <p class="lang_skill">javaScript</p>
- [ ] The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list ul and each of them a li. please implement it

2022-09-25 03:10 UTC, roshan-bajgain commented on index.html
> +            </div>
- [ ] The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list ul and each of them a li. please implement it

2022-09-25 03:10 UTC, roshan-bajgain commented on index.html
> +            </div>
- [ ] The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list ul and each of them a li. please implement it

2022-09-25 03:29 UTC, roshan-bajgain approved these changes
Hi @M1rn4, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-25 03:30 UTC, merged

2022-09-27 14:26 UTC, Kajal19-del commented on index.html
> +<head>
Nice uses of HTML semantic tags

2022-09-27 14:29 UTC, Kajal19-del commented on index.html
> +        </ul>
I think there should be one space line and it's looks beautiful also professional.  :100: